### ISSUE TITLE
Device import fails with missing interface type during push

### ISSUE THREAD

**Issue by erdems** [aruhier/netbox-netprod-importer#33]
Trying to import a QFX device (already added in netbox with mgmt ip and so on):

netbox-netprod-importer import devices.yml -u _netbox -p

The import fails with the following message:

ERROR: netbox_importer: Error when polling device qfx-01-cab4: Interface ae0 could not be created: 400 Client Error: Bad Request for url: https://netbox.lab/api/dcim/interfaces/ -- {'type': ['This field is required.']}

The error seems to be present for any emulated interface, including management/system ones.

**Comment by aruhier** [comment]
Hi,
Thanks for your bug report! Can you try the last release please (v0.3.0) and tell me if it's ok?

Thanks

**Comment by erdems** [comment]
Great job, now the import doesn't fail!

I will check the imported data further and can open a new issue, if required.

Thanks!

**Comment by aruhier** [comment]
Just reopen this one if it's related, no worries.

Thanks for your feedback!
