### ISSUE TITLE
MTU unlimited on Junos MX204

### ISSUE THREAD

**Issue by i4networks** [aruhier/netbox-netprod-importer#35]
ERROR: netbox_importer: Error when polling device junipermx204 : Interface dsc could not be created: 400 Client Error: Bad Request for url: http://localhost:8001/api/dcim/interfaces/88/ -- {'mtu': ['Ensure this value is greater than or equal to 1.']}

run show interfaces dsc 
Physical interface: dsc, Enabled, Physical link is Up
  Interface index: 5, SNMP ifIndex: 5
  Type: Software-Pseudo, **MTU: Unlimited**
  Device flags   : Present Running
  Interface flags: Point-To-Point SNMP-Traps
  Link flags     : None
  Last flapped   : Never
    Input packets : 0
    Output packets: 0

**Comment by aruhier** [comment]
Hi,
I don't really understand: how can the MTU be unlimited? It is a L2 or L3 interface, right?

**Comment by i4networks** [comment]
dsc is the discard interface.. equal  to the cisco ios null0 interface
used in routing to discard trafic

user@host# show routing-options
static {
route 192.0.2.101/32 discard;
route 192.0.2.103/32 discard;
route 192.0.2.105/32 discard;
}

**Comment by aruhier** [comment]
Oh, I see. Ok, let me try something that should workaround this issue.

**Comment by i4networks** [comment]
cool 👍 , love to test it :)

**Comment by aruhier** [comment]
@i4networks: can you test the `nullable_mtu` branch please?

**Comment by i4networks** [comment]
@aruhier  right away!

**Comment by i4networks** [comment]
git clone -b nullable_mtu https://github.com/aruhier/netbox-netprod-importer.git
cd netbox-netprod-importer/
./netbox-netprod-importer import -u i4networks -p -f /root/.config/netbox-netprod-importer/test.yml

**Comment by i4networks** [comment]
./netbox-netprod-importer import -u 88888 -p -f /root/.config/netbox-netprod-importer/test.yml 
 git clone -b nullable_mtu https://github.com/aruhier/netbox-netprod-importer.git
ERROR: netbox_importer: Error when polling device mx204: Interface dsc could not be created: 400 Client Error: Bad Request for url: http://localhost:8001/api/dcim/interfaces/88/ -- {'mtu': ['Ensure this value is greater than or equal to 1.']}

**Comment by aruhier** [comment]
Ok, can you try it again please? I force-pushed a change.

**Comment by i4networks** [comment]
Hi @aruhier 

Succes, MX204 created with no errors and dsc interface with empty MTU in netbox
Thanx for the fix.

**Comment by aruhier** [comment]
Thanks.
